import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, Camera, Globe2, Instagram, Sparkles } from 'lucide-react'

export const metadata = { title: 'Démonstration', description: 'Découvrez un exemple de page créateur réalisée avec TapLinkr.' }

const links = [
  { title: 'Mon nouveau guide créatif', subtitle: 'La méthode complète, édition 2026', primary: true },
  { title: 'Découvrir mon portfolio', subtitle: 'Design, photo et collaborations' },
  { title: 'Les coulisses sur Instagram', subtitle: 'Nouveaux contenus chaque semaine' },
  { title: 'Travaillons ensemble', subtitle: 'Partenariats et projets sur mesure' },
]

export default function DemoPage() {
  return <main className="relative min-h-screen overflow-hidden bg-[#f6efff] px-4 py-8 text-neutral-950 sm:py-12"><div className="absolute inset-0 bg-[radial-gradient(circle_at_15%_10%,rgba(217,70,239,.2),transparent_30%),radial-gradient(circle_at_85%_70%,rgba(34,211,238,.25),transparent_32%)]" /><div className="relative mx-auto max-w-xl"><div className="mb-4 flex items-center justify-between"><Link href="/" className="inline-flex items-center gap-2 rounded-full bg-white/80 px-4 py-2 text-sm font-medium shadow-sm backdrop-blur"><ArrowLeft className="h-4 w-4" /> Retour</Link><span className="rounded-full bg-neutral-950 px-3 py-1.5 text-xs font-semibold text-white">Démonstration</span></div><section className="rounded-[2rem] border border-white/80 bg-white/70 p-5 shadow-2xl shadow-fuchsia-200/50 backdrop-blur-xl sm:p-8"><div className="mx-auto h-24 w-24 rounded-full bg-gradient-to-br from-fuchsia-500 to-cyan-400 p-1"><div className="flex h-full w-full items-center justify-center rounded-full bg-neutral-950 text-white"><Sparkles className="h-8 w-8" /></div></div><div className="mt-5 text-center"><h1 className="text-2xl font-bold">Léa Martin</h1><p className="mt-1 text-sm text-neutral-600">Créatrice · design & lifestyle</p><p className="mx-auto mt-3 max-w-sm text-sm leading-6 text-neutral-600">J’aide les créatifs à transformer leurs idées en projets dont ils sont fiers.</p><div className="mt-4 flex justify-center gap-3"><span className="rounded-full bg-white p-2 shadow-sm"><Instagram className="h-4 w-4" /></span><span className="rounded-full bg-white p-2 shadow-sm"><Camera className="h-4 w-4" /></span><span className="rounded-full bg-white p-2 shadow-sm"><Globe2 className="h-4 w-4" /></span></div></div><div className="mt-7 space-y-3">{links.map((item) => <div key={item.title} className={`group flex items-center justify-between rounded-2xl border p-4 transition hover:-translate-y-0.5 ${item.primary ? 'border-neutral-950 bg-neutral-950 text-white' : 'border-white bg-white/90'}`}><div><p className="font-semibold">{item.title}</p><p className={`mt-1 text-xs ${item.primary ? 'text-white/60' : 'text-neutral-500'}`}>{item.subtitle}</p></div><ArrowUpRight className="h-5 w-5 shrink-0" /></div>)}</div><p className="mt-7 text-center text-xs text-neutral-500">Exemple fictif : aucun lien ne mène vers un service externe.</p></section><div className="mt-5 rounded-2xl bg-neutral-950 p-5 text-center text-white"><p className="font-semibold">Vous voulez une page comme celle-ci ?</p><Link href="/auth/signup" className="mt-3 inline-flex items-center rounded-xl bg-white px-5 py-2.5 text-sm font-semibold text-neutral-950">Créer ma page gratuitement</Link></div></div></main>
}
